FuelLabs/fuel-indexer

.github/workflows/scripts/verify_tag.sh
- This PR copies over the `verify_tag.sh` logic using [fuel-core's verify_tag.sh](https://github.com/FuelLabs/fuel-core/blob/master/.github/workflows/scripts/verify_tag.sh) as a reference 
- This logic actually already existed in a job, but the job never triggered, so there was no error thrown for `verify_tag.sh` not existing.
- This PR simply just adds the script
- Should be a pretty easy PR to eyeball
=> Copy over verify_tag logic

Cargo.lock
This slipped through in #32 as we don't yet use `--locked` in the current CI. I've added the `--locked` check in #31, but need to land this first.
=> Update out-of-date lock file following #32

docs/src/SUMMARY.md, docs/src/api/gql-server.md, docs/src/getting-started/configuration.md, docs/src/getting-started/index.md, fuel-indexer-api-server/Cargo.toml
- This PR adds service CLI opts to the mdbook
- Eventually it would be nice to automate this (similar to forc?) but for now this is fine
- Tracking this in https://github.com/FuelLabs/fuel-indexer/issues/141
- PR also renames the `api_server` binary to `fuel-indexer-api-server` to match convention and updates the docs accordingly
- N/A
=> Add CLI opts to mdbook

fuel-indexer-lib/src/lib.rs, fuel-indexer/src/service.rs
- This PR fixes an issue where the fuel node host that was passed to the indexer service was not properly deriving a `SocketAddr` from the hostname supplied. We already had this `derive_socket_addr` used elsewhere but for whatever reason I forgot to add it to this part of the code. This PR fixes that.
```bash
RUST_LOG=info cargo run --bin fuel-indexer -- \
--postgres-database indexer \
--fuel-node-host node.swayswap.io \
--fuel-node-port 443
```
```bash
RUST_LOG=info cargo run --bin fuel-indexer -- \
--postgres-database indexer \
--fuel-node-host node.swayswap.io \
--fuel-node-port 443
```
=> Fix host resolution in Fuel service

.github/workflows/ci.yml, .gitignore, README.md, config.yaml, docs/src/getting-started/configuration.md, examples/simple-native/src/main.rs, fuel-indexer-lib/src/lib.rs, fuel-indexer-schema/src/db.rs, fuel-indexer-schema/src/db/models.rs, fuel-indexer-schema/src/db/tables.rs, fuel-indexer/src/api.rs, fuel-indexer/src/bin/fuel-indexer.rs, fuel-indexer/src/database.rs, fuel-indexer/src/service.rs, fuel-indexer/tests/test_indexer.rs, scripts/run_migrations.ci.sh, scripts/run_migrations.local.sh
- This PR does a few things
- Adds a `scripts/` folder with the `run_migrations` script(s)
- Adds a `scripts/run_migrations.local.sh` which we can use locally to run migrations
- Changes `run_migrations.sh` to `run_migrations.ci.sh` since this exact format is needed on CI (I'm sure we can combine these files down the road)
- Updates `configuration.md` in the mdbook with the new CLI options
- Important:
- [SQL Features that SQLite does not support](https://www.sqlite.org/omitted.html)
- I added _relationships_ to SQLite but they are _not_ constraints
- I made that decision because the way SQLite works, it would require creating the relationship _constraint_ in the `CREATE` statement. And as everything is setup, we'd have to pass the "is a foriegn key?" logic downstream to where the …
=> Add sqlite constraint support

Cargo.lock, deployment/charts/templates/fuel-indexer-deploy.yaml, docs/src/examples/hello-indexer.md, docs/src/examples/simple-native.md, examples/simple-native/README.md, fuel-indexer-api-server/query_test.sh, fuel-indexer-lib/src/lib.rs, fuel-indexer-schema/Cargo.toml, fuel-indexer-schema/src/db.rs, fuel-indexer/Cargo.toml, fuel-indexer/runnit.sh, fuel-indexer/src/api.rs, fuel-indexer/src/service.rs, fuel-indexer/tests/test_indexer.rs, tests/e2e/composable-indexer/README.md, tests/e2e/composable-indexer/make-test-manifest.bash
- This PR adds a healthcheck at `GET - /health` to the GraphQL API component for Ops monitoring
```bash
➜  curl -v http://0.0.0.0:29987/api/health | json_pp
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 0.0.0.0:29987...
* Connected to 0.0.0.0 (127.0.0.1) port 29987 (#0)
> GET /api/health HTTP/1.1
> Host: 0.0.0.0:29987
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 65
< date: Thu, 01 Sep 2022 00:23:03 GMT
<
{ [65 bytes data]
100    65  100    65    0     0   4850      0 --:--:-- --:--:-- --:--:-- 10833
* Connection #0 to host …
```
=> Add healthcheck endpoint

fuel-indexer/src/api.rs
As detailed in #185, this PR adjusts the calculation of API uptime to use elapsed time.
=> Calculate uptime by using time elapsed since instant

Cargo.lock, fuel-indexer-database/Cargo.toml, fuel-indexer-database/postgres/Cargo.toml, fuel-indexer-database/postgres/src/lib.rs, fuel-indexer-database/sqlite/Cargo.toml, fuel-indexer-database/sqlite/src/lib.rs, fuel-indexer-database/src/lib.rs
Adds retry to database connection attempt so that the indexer service does not immediately crash on start if a connection can't be made. Closes #208.
=> Add retry to database connection

Cargo.lock, fuel-indexer-database/database-types/Cargo.toml, fuel-indexer-database/database-types/src/lib.rs, fuel-indexer-database/postgres/src/lib.rs, fuel-indexer-database/sqlite/src/lib.rs, fuel-indexer-database/src/lib.rs, fuel-indexer-database/src/queries.rs, fuel-indexer-lib/src/lib.rs, fuel-indexer-schema/Cargo.toml, fuel-indexer/src/api.rs, fuel-indexer/src/lib.rs
- Updated version of https://github.com/FuelLabs/fuel-indexer/pull/220
- This PR makes the GraphQL API routes infallible
=> Implement infallible web api routes

fuel-indexer-api-server/src/main.rs, fuel-indexer-database/postgres/src/lib.rs, fuel-indexer-database/sqlite/src/lib.rs, fuel-indexer-database/src/queries.rs, fuel-indexer-lib/src/lib.rs, fuel-indexer-tests/tests/service.rs, fuel-indexer/Cargo.toml, fuel-indexer/src/api.rs, fuel-indexer/src/bin/fuel-indexer.rs, fuel-indexer/src/config.rs, fuel-indexer/src/service.rs
- This PR implements new executor construction after asset upload, thus preventing a service restart
- Unit test is TBD as it would be quite involved (would require its own assets/index/etc)
UAT
```bash
curl -v http://127.0.0.1:29987/api/index/fuel_indexer_test/index1 \
-F "manifest=@fuel-indexer-tests/assets/fuel_indexer_test.yaml" \
-F "wasm=@fuel-indexer-tests/assets/fuel_indexer_test.wasm" \
-F "schema=@fuel-indexer-tests/assets/fuel_indexer_test.graphql" \
-H 'Content-type: multipart/form-data' -H "Authorization: foo" | json_pp
```
```bash
curl -X POST http://127.0.0.1:29987/api/graph/fuel_indexer_test \
-H 'content-type: application/json' \
-d '{"query": "query { message { id ping pong message }}", "params": "b"}' | json_pp
```
=> No restart on asset upload

.github/workflows/ci.yml, Cargo.lock, fuel-indexer-database/Cargo.toml, fuel-indexer-database/database-types/Cargo.toml, fuel-indexer-database/postgres/Cargo.toml, fuel-indexer-database/sqlite/Cargo.toml, fuel-indexer-schema/Cargo.toml, fuel-indexer/Cargo.toml
- Told you this would take 2 or 3 more tries 🥲 
- Per https://github.com/rust-lang/cargo/issues/6738 - publishing _all_ crates now
- Crate reservation for `fuel-indexer-database-types` is at https://github.com/FuelLabs/crate-reservations/pull/12
=> Publish all crates

.github/workflows/ci.yml, docs/src/quickstart/index.md, examples/block-explorer/explorer-index/Cargo.toml, examples/simple-wasm/simple-wasm/Cargo.toml, fuel-indexer-api-server/Cargo.toml, fuel-indexer-database/Cargo.toml, fuel-indexer-database/postgres/Cargo.toml, fuel-indexer-database/sqlite/Cargo.toml, fuel-indexer-macros/Cargo.toml, fuel-indexer-plugin/Cargo.toml, fuel-indexer-schema/Cargo.toml, fuel-indexer-tests/Cargo.toml, fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml, fuel-indexer-tests/components/web/Cargo.toml, fuel-indexer/Cargo.toml
- Gonna give this one last try
- If this doesn't work might have to hold off on a release until the `fuel-indexer-test-web` component is removed in https://github.com/FuelLabs/fuel-indexer/issues/269
=> Add fuel-indexer-test version + make versions more specific

.github/workflows/ci.yml, examples/simple-wasm/simple/Cargo.toml, fuel-indexer-api-server/Cargo.toml, fuel-indexer-macros/Cargo.toml, fuel-indexer-macros/src/indexer.rs, fuel-indexer-plugin/Cargo.toml, fuel-indexer-schema/Cargo.toml, fuel-indexer-tests/components/web/Cargo.toml, fuel-indexer-tests/components/web/src/bin/fuel-node.rs, fuel-indexer-tests/components/web/src/bin/web-api.rs, fuel-indexer-tests/tests/service.rs, fuel-indexer-types/Cargo.toml, fuel-indexer/Cargo.toml
Per Brandon's comment [here](https://fuellabs.slack.com/archives/C01KKBXHATF/p1667439282979879?thread_ts=1667405784.026159&cid=C01KKBXHATF), specifying which crates are publishable and which aren't
=> Specify which crates are publishable

.github/workflows/ci.yml, fuel-indexer-database/database-types/Cargo.toml, fuel-indexer-lib/Cargo.toml, fuel-indexer-types/Cargo.toml
- Yet another v0.1.0 release error
- Turns out this was related to an issue where although the crates build OK and pass CI -- when built in isolation they would fail (thus the release error)
- This PR used [`cargo-make`](https://github.com/sagiegurari/cargo-make) to individually build each crate
- As you can see, a few manifest files had to be updated
- Also introduces the `get-workspace-members` step (same as fuel-rs) in order to build each crate individually on CI going forward
=> v0.1.0-isolate-crates

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, plugins/forc-index/Cargo.toml, plugins/forc-index/README.md, plugins/forc-index/src/bin/forc-index.rs, plugins/forc-index/src/cli.rs, plugins/forc-index/src/commands/deploy.rs, plugins/forc-index/src/commands/init.rs, plugins/forc-index/src/commands/mod.rs, plugins/forc-index/src/commands/new.rs, plugins/forc-index/src/commands/start.rs, plugins/forc-index/src/lib.rs, plugins/forc-index/src/ops/forc_index_deploy.rs, plugins/forc-index/src/ops/forc_index_init.rs, plugins/forc-index/src/ops/forc_index_new.rs, plugins/forc-index/src/ops/forc_index_start.rs, plugins/forc-index/src/ops/mod.rs, plugins/forc-index/src/utils/defaults.rs, plugins/forc-index/src/utils/mod.rs
- This PR adds the long-awaited Forc Indexer plugin that is invoked via `forc index`
- `forc index` is pretty much based on forc in terms of structure
- There may have been a few things that I left out (it's been a minute since I've committed to forc)
- I'm not really sure how to "hook this in" to forc -- so I just built the binary `cargo build --release -p forc-index` and manually added it to my `~/.fuelup/bin`
- This will help with the `forc index start` and `forc index deploy` commands
- This `fuel-indexer` binary has been merged into `fuelup` but haven't had a chance to use it yet
=> Add forc-index plugin

plugins/forc-index/src/ops/forc_index_init.rs, plugins/forc-index/src/utils/mod.rs
- Small bug in the plugin where the project name is not underscored for files/paths
- Schema and manifest filenames should be underscored
=> underscore project name

packages/fuel-indexer/src/service.rs
Closes #380 
Changes
- Starts indexing from block no if defined by `start_block`
```
handler following block values
0 => starts from 1st block
1 => starts from 1st block
>1 => starts from that specific block
>max current block => waits until that block appears
```
- Fixed `next_cursor` logic, if there were no new blocks, the indexer started paginating from `block=1`
=> Add feature `start_block` and fix `next_cursor` logic

.github/workflows/ci.yml
- Release CI time is almost 2 hours. An untenable position
- Don't run cargo tests when publishing release
- Release PRs only contain version changes -- they don't contain new code.
=> update release ci

packages/fuel-indexer-api-server/src/api.rs, packages/fuel-indexer-api-server/src/bin/fuel-indexer-api-server.rs, packages/fuel-indexer-database/src/lib.rs, packages/fuel-indexer-schema/src/db/manager.rs, packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer-tests/tests/database.rs, packages/fuel-indexer/src/bin/fuel-indexer.rs, packages/fuel-indexer/src/service.rs
_Note: This does not fix SQLite; this is just a cleanup PR while I continue to fix the issue._
- Consolidates pool usage across application; we were creating multiple pools across the indexer, which meant that `max_connections()` and other settings weren't being respected
- Adds pool and connection options; we're now able to change pool and connection settings (e.g. log level), if so desired
- Changes some `unwrap()`s to `expect()`s
CI should pass. Starting the service using Postgres should also work as expected.
=> Fix pool usage across the indexer

Cargo.lock, plugins/forc-index/Cargo.toml, plugins/forc-index/src/cli.rs, plugins/forc-index/src/commands/deploy.rs, plugins/forc-index/src/commands/init.rs, plugins/forc-index/src/commands/mod.rs, plugins/forc-index/src/commands/new.rs, plugins/forc-index/src/commands/start.rs, plugins/forc-index/src/commands/stop.rs, plugins/forc-index/src/ops/forc_index_deploy.rs, plugins/forc-index/src/ops/forc_index_stop.rs, plugins/forc-index/src/ops/mod.rs, plugins/forc-index/src/utils/mod.rs
Closes #396.
- Add `forc index stop` command
- Move `extract_manifest_fields` to utils
- Clean up docstrings for other commands
1. `cargo build --release -p forc-index`
2. `cp target/release/forc-index ~/.fuelup/bin`
3. Start an index and verify that it indexes data
4. `forc index stop --manifest [same_manifest_as_running_index] --auth foo`
5. Logging should say that index has been stopped.
6. Verify that indexer no longer indexes data.
=> Add `forc index stop`

packages/fuel-indexer/src/service.rs
- Ensures that currently running handle is aborted if index is redeployed
On master:
1. Start the indexer with an index.
2. Generate test data and verify that data is indexed.
3. `forc index deploy` with the same manifest.
4. `forc index stop` with the same manifest.
5. Generate test data again; one should see that the data is still being indexed.
On this branch:
1. Start the indexer with an index.
2. Generate test data and verify that data is indexed.
3. `forc index deploy` with the same manifest.
4. `forc index stop` with the same manifest.
5. Generate test data again; one should see that the data is **not** indexed.
=> fix (fuel-indexer): Make sure that handle for old executor is aborted on redeploy

.github/workflows/ci.yml
- Remove `actions-rs` in favor of built-in `cargo` and `rustup`
_Apparently_, GitHub Actions has built-in support for `cargo` and `rustup` and since `actions-rs` has been long unmaintained, it seemed like a good idea to try to move over.
=> Remove actions-rs in favor of built-in `cargo` and `rustup`

.github/workflows/ci.yml
It looks like the target flag during the `cargo install cross` step is causing some issues: https://github.com/FuelLabs/fuel-indexer/actions/runs/3898047114/jobs/6657141825
=> fix (CI): Remove `--target` flag from `cargo install cross`

.github/workflows/ci.yml
- Re-add cargo-install action to install `cross`; there seems to be release issues when using the built-in `cargo`
=> fix (CI): Re-add cargo-install action to install `cross`

packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs, packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
Closes #272.
- Adds route to return current block height of test chain
- Adds start block tests for Postgres
- Adds start block tests for SQLite (currently commented out due to #432)
CI should pass with new tests.
=> enhancement (fuel-indexer-tests): Add tests for start block

packages/fuel-indexer-macros/src/schema.rs, packages/fuel-indexer/src/executor.rs, packages/fuel-indexer/src/service.rs, plugins/forc-index/src/commands/start.rs
- This is a cleanup PR to make executor creation more idiomatic by moving that functionality to each executor (`WasmExecutor`, `NativeExecutor`)
- chore: move indexer createion to executors
=> chore: move indexer createion  to executors

docs/README.md, docs/src/quickstart/index.md, plugins/forc-index/src/ops/forc_index_check.rs, plugins/forc-index/src/utils/defaults.rs, scripts/docker-compose.yaml
- This PR fixes a few small bugs
- https://github.com/FuelLabs/fuel-indexer/issues/512
- Uses the latest version tag `v0.2.0` instead of the `latest` tag for the `fuel-indexer` docker image (see https://github.com/FuelLabs/fuel-indexer/issues/513)
- Adds `hash` to the objects in the GraphQL schema for `forc index new`
`forc index check` should now show the proper emoji when an exec is not found:
```text
+--------+------------------------+------------------------------------------------------------------+
| Status |       Component        |                             Details                              |
+--------+------------------------+------------------------------------------------------------------+
|   ⛔️   | fuel-indexer binary    |  Can't locate fuel-indexer …
```
=> fix: various forc index fixes

.github/workflows/ci.yml
- PR updates the version for the notify slack action
- Apparently v1 doesn't use docker any more per [this comment](https://fuellabs.slack.com/archives/C04BQKYTJQJ/p1674760880487909)
=> chore: update notify slack action version

packages/fuel-indexer-database/postgres/build.rs, packages/fuel-indexer-database/sqlite/build.rs
- Add `build.rs` files to database crates that set the `SQLX_OFFLINE` to true if built for [docs.rs](https://docs.rs)
In the [logs for the failing docs.rs builds](https://docs.rs/crate/fuel-indexer/0.2.0/builds/728327), you can see that it fails due to SQLX's compile-time query checking. Since users are unable to set environment variables through `package.metadata.docs.rs`, a `build.rs` file is used to check for the [docs.rs environment](https://github.com/rust-lang/docs.rs/issues/191#issuecomment-654213450) and set the necessary environment variables, which should enable the crate documentation to build successfully.
=> chore: add `build.rs` files for docs.rs

.github/workflows/ci.yml
Closes #543.
Adds `platforms` flag to Docker image build and push steps. 64-bit platforms are covered; see https://github.com/containerd/containerd/blob/v1.4.3/platforms/database.go#L83 for how the platforms are decoded.
See https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images for more information.
There's not a great way to test this on your own computer as it's more for availability's sake. But I was able to build different architectures on my system by running the same commands that are being run in CI. Start by creating a `Dockerfile` with the following content:
```
FROM debian:bullseye-slim
CMD uname -p
```
Enable experimental features on Docker Desktop and build your image normally with the architecture auto-detection: `docker buildx build -t regular_build …
=> enhancement: build docker images for x86_64, ARM, and M1 archs

.github/workflows/ci.yml
Closes #517.
- Add check for successful outcome of `forc index init --namespace fuel` and then `forc index build`
CI should pass. Test locally by `cd`-ing into a new directory and then run `cargo run --bin forc-index init --namespace fuel` followed by `cargo run --bin forc-index build`.
=> ci: add simple CI check for `forc-index` plugin

.github/workflows/ci.yml
Closes #530 
• adds new job `check-rustc` to `ci.yml`
- The run command for the job executes as expected locally. The CI job has ran and successfully updated to `rustc` to 1.67.
- Is the rustc installation in the correct directory / environment for deployment?
=> ci: add check-rustc job

plugins/forc-index/src/commands/init.rs, plugins/forc-index/src/commands/new.rs, plugins/forc-index/src/ops/forc_index_init.rs, plugins/forc-index/src/ops/forc_index_new.rs, plugins/forc-index/src/utils/defaults.rs, plugins/forc-index/src/utils/mod.rs
- This PR defaults `forc index` to using relative paths for assets
- Also adds an `--absolute-paths` flag to `init` and `new` so the user can use absolute paths if they'd like
- enhancement: forc index relative paths
=> enhancement: forc index relative paths

docs/README.md, docs/src/SUMMARY.md, docs/src/quickstart/index.md
- Moves Quickstart below Dependencies in the book
- bugfix: Updates the book's README inclusion to include the now longer README
- remove long line from postgres create output
=> docs: update book + readme

plugins/forc-index/src/ops/forc_index_start.rs
- PR adds `--manifest` flag to `forc index start`
- fix: add manifest to forc-index start
=> fix: add manifest to forc-index start

.github/workflows/ci.yml
- Add a check on CI to no build the plugin if it's a release branch
- You can see that this step works in the positive case, on this test branch's action https://github.com/FuelLabs/fuel-indexer/actions/runs/4204895463/jobs/7296222119
- You can see that this step works in the negative case, on this PR
=> ci: add check-is-release-branch step

ci/Dockerfile.aarch64-unknown-linux-gnu-clang, ci/Dockerfile.x86_64-unknown-linux-gnu-clang, deployment/Dockerfile
- [`v0.3.0` release broke](https://github.com/FuelLabs/fuel-indexer/actions/runs/4206237935) due to non-existent deps
- I'm thinking the base image was changed? But image link in Dockerfile is a 404
- This PR updates Docker deps for `libssl`
- fix: update docker deps
=> fix: update docker deps

.github/workflows/ci.yml, examples/block-explorer/explorer-index/explorer_index.manifest.yaml
- This is the hack we used to push v0.3.0 out
- This was a temporary measure, and needs to be reverted
=> fix: remove tmp ci hack

docs/README.md, docs/src/SUMMARY.md, docs/src/quickstart/index.md
- As previously mentioned, with https://github.com/FuelLabs/fuel-indexer/issues/544 done, we need to de-emphasize Docker for users in our docs
- docs: de-emphasize docker in docs
=> docs: de-emphasize docker in docs

Cargo.lock, examples/block-explorer/explorer-index/Cargo.toml, examples/hello-world-native/hello-index-native/Cargo.toml, examples/hello-world/hello-index/Cargo.toml, examples/hello-world/hello-world-data/Cargo.toml, packages/fuel-indexer-macros/Cargo.toml, packages/fuel-indexer-schema/Cargo.toml, packages/fuel-indexer-tests/Cargo.toml, packages/fuel-indexer-tests/components/fuel-node/Cargo.toml, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml, packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml, packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer-tests/tests/integration/service.rs, packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr, packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr, packages/fuel-indexer-types/Cargo.toml, plugins/forc-index/Cargo.toml, plugins/forc-index/src/utils/defaults.rs
Closes #605.
- Bump SDK version to 0.37.1 so we can re-release `v0.4.0`
=> Bump to SDK version 0.37.1 prior to v0.4.0

.github/workflows/ci.yml
- Removes CI workaround that was added during the use of the SDK WASM hotfix branch
=> chore: remove temp CI forc-index workaround

.github/workflows/ci.yml, packages/fuel-indexer-macros/src/indexer.rs, packages/fuel-indexer-plugin/Cargo.toml, packages/fuel-indexer-tests/components/fuel-node/src/main.rs, packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer-tests/src/lib.rs, packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs, packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
- Adjust CI so that tests and analyses are properly run
-- `cargo fmt --all --check` and `cargo clippy --all-targets` are run across the entire workspace
-- `cargo test --locked --workspace --all-targets --exclude fuel-indexer-tests`: this runs tests through the entire workspace excluding `fuel-indexer-tests`; this is because this command also tests doc-tests, and the path resolution in the use of the `abigen!` macro in `fuel-indexer-tests` causes the tests to fail. Workarounds described in the `cargo test` documentation did not work; this may be due to the structure of the package.
-- Because of the above issue, `cargo test --locked --all-targets --features e2e,postgres -p fuel-indexer-tests` is run in order to test E2E and integration functionality while avoiding triggering the …
=> chore: ensure proper testing and analysis of packages on CI

.github/workflows/ci.yml
- Remove `cargo install sqlx-cli` from the `cargo-verification` and unused dependency check stages of CI
Had a random thought after #600 merged: if we're using `SQLX_OFFLINE=1`, then there would be no compile-time check of the queries; we can probably shave off a couple minutes of CI time by not installing the package for certain steps as it takes an average of 5 minutes on each job.
Update:
- Pre-#600: ~28 mins - https://github.com/FuelLabs/fuel-indexer/actions/runs/4255453841
- Post-#600, pre-#618: ~21 mins - https://github.com/FuelLabs/fuel-indexer/actions/runs/4263521437
- Runtime of #618: ~16 mins - https://github.com/FuelLabs/fuel-indexer/actions/runs/4258854184
Almost a 45% reduction in CI run time when coupled with #600.
=> chore: remove `sqlx-cli` install from certain CI steps

.github/workflows/ci.yml, deployment/Dockerfile
- We should be including `fuel-core-lib` in our release builds
- This was tested in a previous (now squashed) commit
- If you want to test for yourself, just remove the `if:` condition from the `publish-docker-image` step in this PR
- chore: add fuel-core to indexer release builds
=> chore: add fuel-core to indexer release builds

packages/fuel-indexer/src/service.rs
- Kill old execution module if deploying a new execution module under the same namespace and identifier
0. Ensure database is clear and build `forc-index`: `cargo build -p forc-index`.
1. Add log message to `examples/block-explorer/explorer-index/src/lib.rs`; something like "FIRST" will suffice.
2. Deploy explorer index:
```
../../target/debug/forc-index deploy \                                                      
--path explorer-index \
--output-dir-root [whatever your fuel-indexer repo root is] \
--url http://0.0.0.0:29987 \
--target wasm32-unknown-unknown
```
3. Change log message in explorer example to something different, e.g. "SECOND".
4. Re-deploy using same command.
5. Search through service logs; you should see that both messages are being logged.
Repeat the above steps, you …
=> fix: kill old execution module when redeploying under same namespace and identifier

docs/src/examples/block-explorer.md
- Fix improper include in block explorer example section of book
Pull down the branch, change into the `docs` directory, and run `mdbook serve`. Check the block explorer section to verify that the code is properly included now.
=> docs: fix block explorer embed in book

.github/workflows/ci.yml
- In Github actions a job is skipped if any one of it's dependencies is skipped, even if the `if:` statement of the job evaluates true
- So we need to unskip the docker/publish jobs by removing their skipped dependencies
=> fix: remove skipped dependent jobs for master/release

.github/workflows/ci.yml, deployment/Dockerfile
- `--fuel-core-lib` is a feature that only applies to `fuel-indexer`, not `fuel-indexer-api-server`
- For now, just remove the feature from the Docker build, we can add it back later when we decide if we want to also add the feature to `fuel-indexer-api-server`
=> remove --fuel-core-lib from Dockerfile

.github/workflows/ci.yml
- Remove Postgres from the `services` for `cargo-verifications`
- Re-add `fuel-indexer` to package strategy matrix for `cargo-verifications`
- Add additional requirements to `validation-complete` step
@Voxelot mentioned that we're pulling Postgres in on the build step for each package. However, we're not leveraging the database at all during the build step as we've disabled SQLx's compile-time query checking. So in order to reduce the frequency of rate limit errors, I'm removing Postgres from the build step.
=> ci: remove Postgres service from cargo-verifications build step

packages/fuel-indexer/src/executor.rs
- Iterate blocks in proper ascending order
CI should pass. All this does is change the order of incoming blocks into executors from:
```
10, 9, 8, 7, 6, 5, ...
20, 19, 18, 17, 16, 15 ...
```
to:
```
1, 2, 3, 4, 5, ...
11, 12, 13, 14, 15, ...
```
You can notice the change by running the block explorer example pointed to either of the testnet chains. On master, they come in the former order. On this branch, they come in the latter order.
We originally had the `.rev()` call on the iterator as the fuel node client originally sent them to the indexer in the reverse order. In all the other work that we've done, we've forgotten to go back and remove it.
=> chore: iterate blocks in proper ascending order

packages/fuel-indexer-macros/src/indexer.rs, packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
- Safely decode type ID and data from `data` field of `MessageOut` receipt
We can't create a test for this just yet as I don't know how someone was able to generate an empty data field. It was suggested that one can use an empty `Bytes` array to trigger it, but I was unable to get it working. In any case, this should solve our issues in which the indexer was crashing on the beta-3 testnet.
0. Build WASM modules and ensure DB is cleared.
1. Run examples on beta-2; indexers should work as expected.
2. Run examples on beta-3; indexers should work as expected.
This error was caused by a `MessageOut` receipt with an empty hex string for the `data` field:
```
{
"receiptType": "MESSAGE_OUT",
"recipient": "0x000000000000000000000000172eda4e99d41a97d7c1849a8d05f46de9eeb8dc",
"sender": …
```
=> fix: do not panic when there is an empty data field in `MessageOut` receipt

ci/Dockerfile.fuel-node, deployment/Dockerfile
The docker image being pulled in `Dockerfile.fuel-node` was using rust `1.67` `lukemathwalker/cargo-chef` has the latest available `1.68.1`. This bumps it and should resolve the X on master CI. 
I am unable to test this locally due to M1 build problem.
=> chore: bump docker image version

packages/fuel-indexer-tests/Cargo.toml, packages/fuel-indexer/Cargo.toml
- Upgrade `wasmer` from `v2.0` to `v2.3`
Tests should pass. Each example should pass as well.
_No changes in functionality_; this is just an upgrade to bring in some fixes for memory leaks and the like that have been added after `wasmer`'s `v2.0` release. We should still investigate refactoring to use `v3.0` or above, just at a later time.
=> chore: upgrade `wasmer` to v2.3.0

config.yaml, deployment/charts/templates/fuel-indexer-deployment.yaml, docs/src/getting-started/starting-the-fuel-indexer.md, docs/src/reference-guide/components/graphql/api-server.md, packages/fuel-indexer-api-server/src/cli.rs, packages/fuel-indexer-api-server/src/commands/run.rs, packages/fuel-indexer-database/postgres/src/lib.rs, packages/fuel-indexer-database/src/lib.rs, packages/fuel-indexer-lib/src/config/database.rs, packages/fuel-indexer-lib/src/config/mod.rs, packages/fuel-indexer-lib/src/defaults.rs, packages/fuel-indexer-lib/src/utils.rs, packages/fuel-indexer-plugin/src/lib.rs, packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer/src/cli.rs, packages/fuel-indexer/src/commands/run.rs, packages/fuel-indexer/src/service.rs, plugins/forc-index/src/ops/forc_index_start.rs, plugins/forc-postgres/src/ops/forc_postgres_createdb.rs
- PR adds `-v --verbose` flag to `fuel-indexer` and `fuel-indexer-api-server`
- Updates docs accordingly
- Ensure `forc-index start` points to a latest `fuel-indexer` binary
- Run with verbose logging
```bash
cargo run --bin fuel-indexer -- run \
--fuel-node-host beta-3.fuel.network \
--fuel-node-port 80 \
--manifest examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml \
--verbose
```
```
cargo run --bin forc-index -- start -v
```
- enhancement: make verbose logging configurable
=> enhancement: make verbose logging configurable

.github/workflows/ci.yml
- Ensure that `cargo-test-forc-index-plugins` CI step only tests the plugins
- Remove unnecessary exclusions
- Remove `check-forc-index` as it's superseded by `cargo-test-forc-index-plugins`
`cargo-test-forc-index-plugins` was testing the entire workspace _and_ running each test sequentially. This changes that step so that it only runs the plugin tests.
=> chore: fix CI commands for plugin tests

plugins/forc-index/src/ops/forc_index_start.rs
- This PR makes a small change to pass the `persistent: true` param to the `CreateDbCommand` command used by `for index start`
- Previously the DB was being created but not persisted, thus resulting in an error
- Ensure `fore-index start` points at your local `fuel-indexer` binary 
```bash
./target/release/forc-index start \
--embedded-database \
--fuel-node-host beta-3.fuel.network \
--fuel-node-port 80 \
--run-migrations \
--manifest examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml
```
- One `master` this command ☝🏽 will fail
- fix: persist embedded db when flag is passed
=> fix: persist embedded db when flag is passed

packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs, packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs, packages/fuel-indexer-tests/tests/integration/service.rs, packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs, packages/fuel-indexer-tests/tests/lib.rs, packages/fuel-indexer/src/commands/run.rs, plugins/forc-index/src/ops/forc_index_auth.rs, plugins/forc-index/src/ops/forc_index_start.rs
- PR fixes a bug that was preventing the fuel-node for running (it was starting but the coroutine wasn't being awaited)
- Also adds `clippy` back to the tests
- On master running the service should show that the service never actually connects to the fuel node
- fix: await fuel-core service when using --local-fuel-node
=> fix: await fuel-core service when using --local-fuel-node

.github/workflows/ci.yml
- CI will pass after v0.7.0 is released https://github.com/FuelLabs/fuel-indexer/actions/runs/4630450012
=> ci: remove merge queue

Cargo.lock, examples/block-explorer/explorer-indexer/Cargo.toml, examples/hello-world-native/hello-indexer-native/Cargo.toml, examples/hello-world/hello-indexer/Cargo.toml, packages/fuel-indexer-macros/src/indexer.rs, packages/fuel-indexer-macros/src/native.rs, packages/fuel-indexer-macros/src/wasm.rs, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs, packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml, packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Closes #722.
- Compute `message_id` from `MessageOut` receipt fields
- Fix a bug in which the message data from the receipt was being indexed but not the receipt itself
- Fix errant re-name of one of our E2E tests
CI should pass. Since the message ID is different on every pass, I couldn't add an assertion to the E2E test. But if you want to be sure that the calculated message ID is exactly the same as the one in the receipt, feel free to replace the first two lines of the `Receipt::MessageOut` match arm with the following:
```
Receipt::MessageOut { sender, recipient, amount, nonce, len, digest, data, message_id } => {
let computed_message_id = decoder.compute_message_id(&sender, &recipient, nonce, amount, &data[..]);
Logger::warn!(&format!("These two message IDs should match:\nmessage id …
```
=> enhancement: compute message ID by using `MessageOut` receipt fields

.github/workflows/ci.yml, config.yaml, docs/QUICKSTART.md, docs/src/getting-started/starting-the-fuel-indexer.md, docs/src/reference-guide/components/assets/manifest.md, examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml, examples/hello-world-native/hello-indexer-native/hello_indexer_native.manifest.yaml, examples/hello-world/hello-indexer/hello_indexer.manifest.yaml, packages/fuel-indexer-lib/src/config/mod.rs, packages/fuel-indexer-lib/src/defaults.rs, packages/fuel-indexer-lib/src/manifest.rs, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml, packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer/src/executor.rs, packages/fuel-indexer/src/lib.rs
- PR adds `fuel_node` param to indexer manifest and `--indexer-net-config` config opt to the indexer service
- `--indexer-net-config` is set by the indexer operator, and allows indexers uploaded with a `fuel_client` manifest param to connect to that particular indexer's Fuel client address (as opposed to the indexer operator's Fuel client address)
- I think the `--indexer-net-config` is necessary because flag because an indexer operator should decide whether they want to support this functionality.
- If the indexer operator _does not_ use the `--indexer-net-config` flag, then whatever is specified in the `fuel_client` param of an indexer manifest will be ignored
```bash
cargo run --bin fuel-indexer -- run \
--indexer-net-config \
--manifest …
```
=> enhancement: allow network config from manifest

Cargo.lock, packages/fuel-indexer-api-server/Cargo.toml, packages/fuel-indexer-api-server/src/api.rs, packages/fuel-indexer-api-server/src/uses.rs, plugins/forc-index/src/ops/forc_index_auth.rs
- PR fixes an authentication bug by decoding the message signatures before trying to derive a signature
- Everything should work the first time (and every subsequent time)
- fix: decode auth signature before recovery
=>  fix: decode auth signature before recovery

packages/fuel-indexer-schema/src/db/arguments.rs, packages/fuel-indexer-schema/src/db/graphql.rs, packages/fuel-indexer-schema/src/db/queries.rs, packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs, packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Closes #656.
- Add doc comments in a number of places
- Rename a number of structs and variables for clarity
- Add `QueryParams` struct to associate potential parameters together
- Add `to_sql()` method for each query parameter type
- Add support for `order` keyword; this allows for sorting a list of results by a field
- Add support for `first` keyword; this allows for limiting a result set to the first N records
- Add support for `offset` keyword; this allows for skipping the first N records in a result set
- Add tests for new keywords
0. Compile fresh WASM modules and clear database.
1. `cargo run --bin fuel-indexer -- run --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --manifest examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml`
2. Open …
=> enhancement: add sorting and offset-based pagination to GraphQL API queries

packages/fuel-indexer-api-server/src/api.rs, packages/fuel-indexer-api-server/src/uses.rs, packages/fuel-indexer-schema/src/db/arguments.rs, packages/fuel-indexer-schema/src/db/graphql.rs, packages/fuel-indexer-schema/src/db/queries.rs, packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs, packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
- Adds `PageInfo` object to paginated GraphQL responses
- Adjusts SQL query for paginated GraphQL requests
- Adds support for aliased fields
- Adjust tests
- Adjust doc comments
- Adds match arm in `ApiError` for `GraphQlError`
0. Compile fresh WASM modules and clear database.
1. `cargo run --bin fuel-indexer -- run --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --manifest examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml`
2. Open the corresponding playground: `http://localhost:29987/api/playground/fuel_examples/explorer_indexer`
3. Run the following query.
```
query {
blocks: block(order: { desc: height}, first: 5, offset: 5) {
id
hash
height
timestamp
}
}
```
You should see that the last 5 blocks are shown in reverse order of block height …
=> enhancement: add `PageInfo` object to paginated GraphQL responses

examples/block-explorer/docker-compose.yaml, examples/hello-world/docker-compose.yaml
- PR adds `--run-migrations` to the docker compose `run` commands
- fix: run migrations in docker compose
=> fix: run migrations in docker compose

docs/src/getting-started/dependencies/wasm.md
- Had an experience today where a user missed the link in the docs and just forgot to follow the additional WASM dependency steps. 
- PR makes the WASM dependency notes more visible
- docs: swap link for copy/paste of m1 text in book
=> docs: swap link for copy/paste of m1 text in book

.github/workflows/ci.yml
Closes #468.
- Deprecate actions-rs for dtolnay/rust-toolchain
@bingcicle made the same change over on https://github.com/FuelLabs/fuelup/pull/430 with no apparent regressions.
=> chore: deprecate `actions-rs` for `dtolnay/rust-toolchain`

.github/workflows/ci.yml, packages/fuel-indexer-graphql/Cargo.toml, packages/fuel-indexer-macros/Cargo.toml, packages/fuel-indexer-plugin/Cargo.toml
This is blocking the full publishing of the `fuel-indexer-*` crates.
- Add `db-models` feature to `fuel-indexer-schema` dependency in `fuel-indexer-graphql`
- Remove unnecessary `default-features = false` on dependencies to get rid of warnings
=> bug: fix feature flag on `fuel-indexer-schema` for `fuel-indexer-graphql`

packages/fuel-indexer-lib/src/manifest.rs
Closes #827 
1. Rebuild wasm binaries and refresh the db. 
2. Rebuild the plugin binary `cargo build -p forc-index -p fuel-indexer --release --features fuel-core-lib`
3. Run the indexer and run the local fuel-node.
3. Run the command (this command before was producing the `""` in the yaml). 
`./target/release/forc-index deploy --path examples/block-explorer/explorer-indexer`
4. In `explorer_indexer.manifest.yaml` check that `contract_id: ~` and *not* `contract_id: ""`
=> bugfix: fix deserialize bug on contract_id

Cargo.toml
Closes #842.
- Introduce `[default-members]` section
- Change member inclusion to be more idiomatic
This change was done to prevent the issue of failed builds when running `cargo build` in the repository root. This structure comes from the [`axum` project](https://github.com/tokio-rs/axum/blob/main/Cargo.toml).
This change also reduces the overall build time of a bare `cargo build`, but makes changes to using the internal testing components. To use internal testing components, a dev should use `cargo run -p [package] --bin [package]`. So in this case of `fuel-node`, one would start it by using `cargo run -p fuel-node --bin fuel-node`.
=> chore: use `[default-members]` section in `Cargo.toml`

fuel-toolchain.toml
Only way to test this is to try redeploying it to our production environment. 
If I run at the root:
`forc --version` 
I see `0.37.0`
If I run `forc --version`  in some other dir I see `0.38.0` so this correctly pins the version. 
I don't think this will fix the bug. But thought its interesting because of [this](https://fuellabs.slack.com/archives/C031TTYJM60/p1682627834906569). Useful to know we can pin forc versions, I didn't know it was possible prior to reading that thread.
=> bugfix: try pinning toolchain version

docs/src/reference-guide/authentication/index.md
- Added `wallet` into example prompt for documentation
Now that [Update password input message](https://github.com/FuelLabs/forc-wallet/issues/111) is merged we can update the docs for the example input that the user will see - once we bump versions to use this change
Closes #838
=> `auth` password input message 

Cargo.lock, examples/hello-world-native/hello-indexer-native/src/main.rs, examples/hello-world/hello-indexer/src/lib.rs, packages/fuel-indexer-schema/src/lib.rs, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs, packages/fuel-indexer-types/Cargo.toml, packages/fuel-indexer-types/src/lib.rs
Closes #843
• Adds the macros`json_impl` and `blob_impl` macros for custom Scalar types. 
• Adds unit tests testing the underlying types of our scalar types.
• Changes the type of Blob from an alias to a custom type (see note below about this)
• Updates code elsewhere to integrate the Blob type. 
I had to make Blob a custom type as apposed to just an alias as it was before. This is because I could not implement a custom `From` trait on an alias of underlying type`Vec<u8>`. But when `Blob is :
```rust
pub struct Blob(pub Vec<u8>);
```
I can implement the From trait. This is because of the orphan rule.
##Testing
This unit test wont run in CI. I don't think we need it to necessarily, but to run the tests cd into 
`packages/fuel-indexer-types/src/` and run `cargo test` this will run the newly …
=> enhancement: convert Scalar types into `Json` and `Blob`

Cargo.lock, packages/fuel-indexer-api-server/src/uses.rs, packages/fuel-indexer-database/postgres/src/lib.rs, packages/fuel-indexer-database/src/queries.rs, packages/fuel-indexer-lib/src/utils.rs, packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs, packages/fuel-indexer/src/service.rs
- PR fixes a bug with `forc index revert`
- Previously `revert` was sending the entire WASM blob over the channel (👎🏽 ) which might have been crashing the channel and closing it
- This PR fixes that by moving the "delete" portion of this to the use-case/handler, and loading the wasm bytes inside the service task (so that only the indexer identifier and namespace are sent over the channel)
- Also renames queries as a part of https://github.com/FuelLabs/fuel-indexer/issues/643
- ⚠️ We won't be able to test for sure that this works til we deploy to beta-3-indexer (after merge to master)
- But we can still confirm the change locally
- fix: don't send wasm bytes over service channel
=> fix: don't send wasm bytes over service channel

ci/Dockerfile.fuel-node, examples/hello-world-native/README.md, examples/hello-world-native/hello-indexer-native/Cargo.toml, examples/hello-world/README.md, packages/fuel-indexer-lib/src/manifest.rs, packages/fuel-indexer-macros/src/indexer.rs, plugins/forc-index/src/ops/forc_index_deploy.rs, plugins/forc-index/src/utils/defaults.rs
- PR does a few things
- Updates docs for the examples
- Removes `api-server` and `fuel-core-lib` feature flagging from native execution
- Fixes a bug in `forc index deploy` where the `--path` isn't respected relative to the `--target-dir`
- This ☝🏽 would fail on master
- docs: update docs for examples 
- fix: ensure that `forc index deploy` respects `--path` relative to `--target-dir`
=> fix: update docs/examples

plugins/forc-index/src/utils/defaults.rs
Updates missing default field for `forc index`.
=> chore: add end_block to default forc index manifest

docs/README.md, docs/src/reference-guide/components/graphql/index.md
Closes #904.
- Adds a table that describes our GraphQL current and future functionality as well as what we won't add
CI should pass; only documentation was added
- https://github.com/FuelLabs/fuel-indexer/commit/d82d28d1791babd274883a26770308396cadf8f7 - introduce table to docs
Regarding the planned or in-progress bits, I added what I've heard being mentioned over the last couple months. I'm not tied to any of it; just added it to flesh things out.
=> docs: add GraphQL functionality table

packages/fuel-indexer-graphql/src/dynamic.rs
Fixes introspection response nesting.
CI should pass. Start the explorer indexer and open the playground link. Open developer tools and inspect the response for the introspection query. Introspection results should be under the `data` key. On master, they're currently under `data['data']`.
- Fix introspection response nesting
=> fix: introspection response was nested one level too deep

Cargo.lock, packages/fuel-indexer-graphql/src/dynamic.rs, packages/fuel-indexer-graphql/src/graphql.rs, packages/fuel-indexer-schema/src/db/tables.rs, packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Fixes doc and schema type generation for playground after we've added GraphQL enum support
On master:
- Clear database and compile fresh `fuel-indexer-test` WASM module.
- ` cargo run --bin fuel-indexer -- run --manifest packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml --run-migrations`
- Open the playground link for `fuel-indexer-test`: `http://localhost:29987/api/playground/fuel_indexer_test/index1`
Open the docs or schema tabs; they should be broken. There should also be an error as soon as you open the page.
On this branch:
Repeat the same steps on this branch; there should be no errors at all and the docs/schema tabs should work properly.
- [Add hashset for non-indexable types, e.g. …
=> fix: fix docs and schema type generation for playground

packages/fuel-indexer-macros/src/helpers.rs, packages/fuel-indexer-macros/src/schema.rs, packages/fuel-indexer-schema/src/lib.rs, packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments_none_types-19.snap, packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments_some_types-20.snap
_Note: This is being merged into a feature branch._
Allows for list types to be properly decoded in the schema macro. Note that this does not implement querying for list types, which will come at a later time.
CI should pass as there should be no outward changes just yet. Proper tests will be added to the feature branch at a later time.
Using the `hello-indexer` example, ensure that the WASM module builds with no errors for the four possible cases:
1. Non-nullable list of non-nullable elements (`Vec<FtColumn>`):
- Add the following to the `Salutation` entity in the schema: `words: [Charfield!]!`
- Add the following line to the `Salutation` struct in the handler: `words: vec!["Hello".to_string()]`
- Ensure that `cargo build` completes successfully.
2. Non-nullable list of nullable elements …
=> enhancement: support list types in schema macro

docs/src/reference-guide/indexing/blocks-and-transactions.md, examples/fuel-explorer/docker-compose.yaml, examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql, examples/fuel-explorer/fuel-explorer/src/lib.rs, packages/fuel-indexer-macros/src/indexer.rs, packages/fuel-indexer-macros/src/schema.rs, packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs, packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr, packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs, packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr, packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs, packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs, packages/fuel-indexer-types/src/io.rs, packages/fuel-indexer-types/src/lib.rs, packages/fuel-indexer-types/src/transaction.rs, packages/fuel-indexer/src/executor.rs, scripts/docker-compose.yaml
- PR implements more types from the block explorer 🥲 
- A lot of copy/pasta because #286 
- enhancement: implement more explorer types
=> enhancement: implement more types

packages/fuel-indexer-api-server/src/uses.rs, packages/fuel-indexer-database/postgres/src/lib.rs, packages/fuel-indexer-lib/src/defaults.rs, packages/fuel-indexer/src/database.rs, packages/fuel-indexer/src/executor.rs
- PR extends indexer timeout, and tries to re-establish a transaction on `put_object` and `get_object`
- Playground is crashing due to error:
```text
2023-05-26T15:31:15.306379Z  INFO fuel_indexer::ffi: 110: Handling a transaction (>'.')>
2023-05-26T15:31:15.307022Z ERROR fuel_indexer::executor: 562: WasmIndexExecutor handle_events timed out: Elapsed(()).
2023-05-26T15:31:15.307104Z  INFO sqlx::query: INSERT INTO fuel_indexer_test.transaction (id, …; rows affected: 1, rows returned: 0, elapsed: 282.167µs
INSERT INTO
fuel_indexer_test.transaction (id, block, hash, object)
VALUES
(
3991704639109347385,
7017841000420106850,
'dd744ec3eccfabfaf991f893d4c20d4e759a8e98cb1da40bce13d0a9a7a6883b',
$1 :: bytea
) ON CONFLICT(id) DO
UPDATE
SET
block = 7017841000420106850,
hash = …
```
=> fix: bump default indexer timeout + cleanup transaction creation in DB

packages/fuel-indexer-lib/src/utils.rs, packages/fuel-indexer-macros/src/indexer.rs, packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr, packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr, packages/fuel-indexer/src/commands/run.rs, packages/fuel-indexer/src/database.rs
When debugging a separate issue with full blocks, it was quite difficult to parse through the output as certain macro and database logs were printed for each contract and transaction in the block. As such, I elected to place said logs at the `DEBUG` log level so that users could more easily find the logs from their indexer modules.
CI should pass. You can see the debug logs by appending `RUST_LOG="debug"` to the beginning of `fuel-indexer run`.
- [Move 'unknown X; check Y' type logs to debug; move stash conn log to debug](https://github.com/FuelLabs/fuel-indexer/commit/2a6c7508897d124cb4894d55e8005f06f37d7bc9)
- [Do not print playground link when starting without a manifest](https://github.com/FuelLabs/fuel-indexer/commit/ca6710d9499215fd6d0015cd9cc56979fe38c6a6)
=> chore: reduce log spam

Cargo.lock, packages/fuel-indexer-macros/Cargo.toml
Somehow `fuel-indexer-utils` made it back into the `Cargo.toml` as we pushed changes.
=> fix: remove `fuel-indexer-utils` from `fuel-indexer-macros` Cargo.toml

.github/workflows/ci.yml
Closes #971.
Removes successful binary and Docker image publishing as dependencies for crate publishing.
[Remove dependency on binary and Docker image publish for crate publis…](https://github.com/FuelLabs/fuel-indexer/commit/87bd2cacd900d5041f8229c33bc939e4625fab96)
=> ci: streamline crate publishing workflow

packages/fuel-indexer-api-server/src/models.rs, packages/fuel-indexer-api-server/src/uses.rs, packages/fuel-indexer-database/postgres/src/lib.rs
- Whilst deploying an indexer to the playground I noticed authentication was buggy
- This PR fixes 3 issues:
- Removes auth from `register_indexer_assets`
- Fixes sqlx type issue in `queries::indexer_owned_by`
- Uses the public key in `index_registry` (not the issuer)
- This was previously unnoticed cause I never run the indexer locally with auth (will change that going forward)
- Obviously an integration test would help here. Happy for anyone to open that PR ;) 
```bash
cargo run --bin fuel-indexer -- run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --auth-enabled --auth-strategy jwt --jwt-secret abcdefg --jwt-issuer FuelLabs
```
- On master this fails due to the SQLx type issue _and_ the unnecessary authentication check
- This will fail as `Unauthorized`
- …
=> fix: various auth updates

packages/fuel-indexer/src/database.rs
- If for whatever reason `put_object` fails, we currently panic
- We should allow for the failure gracefully
- Error is:
```text
2023-06-07T01:01:50.452282Z  INFO sqlx::query: INSERT INTO fuel_indexer_test.transaction (id, …; rows affected: 1, rows returned: 0, elapsed: 1.063ms
INSERT INTO
fuel_indexer_test.transaction (id, block, hash, object)
VALUES
(
7005739969560339248,
3761688992633087027,
'18c478c3b5bbc51ba76bc3372b4593599295d591f885bf3ec354b3e14a492444',
$1 :: bytea
) ON CONFLICT(id) DO
UPDATE
SET
id = 7005739969560339248,
block = 3761688992633087027,
hash = '18c478c3b5bbc51ba76bc3372b4593599295d591f885bf3ec354b3e14a492444'
thread 'tokio-runtime-worker' panicked at 'Failed to put object.: Database(PgDatabaseError { severity: Error, code: "23503", message: "insert or update on table …
```
=> fix: don't panic on failed put_object

plugins/forc-index/src/utils/defaults.rs
- Too much log spam on the default indexer
- Also, using `block_data.id` (the actual block ID) as the join field for consistency with fuel-core 
=> chore: small default indexer updates

examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql, examples/fuel-explorer/fuel-explorer/src/lib.rs, packages/fuel-indexer-macros/src/helpers.rs, packages/fuel-indexer-macros/src/schema.rs, packages/fuel-indexer-schema/src/parser.rs
This PR adds instantiation helpers to GraphQL union types.
CI should pass. There aren't any real testing steps here; as a proof, in the `fuel-explorer` example, the instantiation for the `Consensus` type has been changed to leverage the new instantiation functionality implemented by this PR. Feel free to make the same changes on `develop` and verify that they do not work there and that the changes *do* work on this branch.
- Add `From` trait impls to each member of a union type
-- Add `generate_from_traits_for_union` helper
-- Combine instantiation trait generators into the flow of `generate_object_trait_impls`
- Add `field_type_optionality` to `ParsedGraphQLSchema` to easily determine field nullability
=> enhancement: add instantiation helpers for union types

plugins/forc-index/src/utils/defaults.rs
- Default indexer was not updated properly with new block height type
- `forc index new && forc index build`
- fix: update default indexer schema type
=> fix: update default indexer schema type

packages/fuel-indexer/src/ffi.rs
Since `get_object` and `put_object` are called inside the context of a `tokio` runtime, we can reuse it with `tokio::runtime::Handle::current()`
This _seems_ to improve both the stability and performance when running the indexer on my laptop. Also, we shouldn't ever see this anymore:
```
2023-07-03T16:09:43.068240Z ERROR fuel_indexer::database: 162: Failed to put object: Io(Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown." })
2023-07-03T16:09:43.068544Z ERROR fuel_indexer::database: 162: Failed to put object: Io(Custom { kind: Other, error: "A Tokio 1.x context was found, but it is being shutdown." })
2023-07-03T16:09:43.068953Z ERROR fuel_indexer::database: 162: Failed to put object: Io(Custom { kind: Other, error: "A Tokio 1.x context was found, but …
```
=> use tokio::runtime::Handle::current() in get_object and put_object

packages/fuel-indexer-lib/src/graphql/parser.rs, packages/fuel-indexer-schema/src/db/tables.rs
Ensures that unions are added to the query root so that they are available for querying.
On develop:
- Start the fuel-explorer example, open up the playground, and attempt to run the following query:
```
query {
transaction(order: { id: desc }, first: 5) {
id
}
}
```
- You should see an error.
On this branch:
- Repeat the steps above. You should see the results shown properly.
=> fix: ensure that unions are added to query root

packages/fuel-indexer-database/database-types/src/lib.rs, packages/fuel-indexer-graphql/src/arguments.rs, packages/fuel-indexer-graphql/src/dynamic.rs, packages/fuel-indexer-graphql/src/graphql.rs, packages/fuel-indexer-lib/src/graphql/parser.rs, packages/fuel-indexer-macros/src/decoder.rs, packages/fuel-indexer-schema/src/db/tables.rs, packages/fuel-indexer-schema/src/lib.rs, packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Removes dependence on the concept of a `QueryRoot` in queries and schema construction.
CI should pass. All functionality should still be the same; this should have no outward effect on the user.
=> chore: Remove `QueryRoot` workaround

.cargo/config, .github/workflows/ci.yml, deployment/Dockerfile, examples/fuel-explorer/README.md, examples/fuel-explorer/docker-compose.yaml, examples/hello-world/README.md, examples/hello-world/docker-compose.yaml, examples/hello-world/hello-world-node/src/main.rs
- Adds cross platform support to our docker builds
- Based on fuel-core example https://github.com/FuelLabs/fuel-core/pull/1233
- [Previously the docker build step used to take around ~40 mins](https://github.com/FuelLabs/fuel-indexer/actions/runs/5509952533/jobs/10043437988)
- With this change this step now takes around 60 mins
- Twice as long cause it's building two images
- That image is here https://github.com/FuelLabs/fuel-indexer/pkgs/container/fuel-indexer/108693557?tag=sha-e99a5b9
- You should be able to pull down this image and run it on a `aarch64-apple-darwin` target 
- `cd examples/hello-world && docker compose up`
- chore: add docker multiplatform support
=> chore: add docker multiplatform

packages/fuel-indexer-graphql/src/graphql.rs
Remove a use of `.expect()` in the control flow for GraphQL queries.
CI should pass. This change propagates an error to the user instead of crashing the indexer service.
=> chore: remove `.expect()` from GraphQL query flow

packages/fuel-indexer/src/executor.rs
This PR fixes unreported Runtime errors. There are three levels of errors from `handle_events`: elapsed, join error, or (WASM) runtime error. Currently, on `develop`, the runtime error is not reported.
Set `start_block: 8322` in `fuel-explorer` and run:
```
cargo run -p fuel-indexer -- run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --manifest examples/fuel-explorer/fuel-explorer/fuel_explorer.manifest.yaml --replace-indexer
```
On `develop`, there is no error. On this branch, `fuel-explorer` fails.
See #1090 for additional information.
* Report WASM runtime errors from WasmIndexExecutor
=> Fix unreported WASM runtime error

packages/fuel-indexer/src/executor.rs
- PR bumps the executor's cursor, in order to move to the next set of data, when a sqlx constraint error is encountered. More info in https://github.com/FuelLabs/fuel-indexer/issues/1083
- On develop, you will see the sqlx constraint error happens 10 times, and the executor dies
- More info in https://github.com/FuelLabs/fuel-indexer/issues/1083
- fix: bump cursor when unique constraint fails due to ID derivation
=> fix: bump cursor when unique constraint fails due to ID derivation

packages/fuel-indexer-macros/src/decoder.rs, packages/fuel-indexer-types/src/fuel.rs, packages/fuel-indexer/src/ffi.rs
- Prevents from panic'ing when `put_object` fails. 
- Currently this crashes the entire service
- Why does it fail? Not sure, but we can't bring down the entire service because of this
- We successfully indexed 178,775 blocks before encountering this error - some type of blip?
- [Here is the elastic doc with the exact error](https://search-fuel-prod-sp5nn3gesvhmb5qjjcxarse5di.us-east-1.es.amazonaws.com/_dashboards/app/discover#/doc/a9bb0e30-7cfa-11ed-bb0a-9d1026406ebc/cwl-2023.07.12?id=37670455749185772964673089726982812396625972086305981568)
```bash
cargo run -p fuel-indexer -- run --run-migrations --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --replace-indexer
```
- fix: prevent serde error from crashing service
=> fix: prevent serde error from crashing service

.github/workflows/ci.yml
This PR makes a number of changes to the CI pipeline:
- `cargo build`, `cargo clippy`, and `cargo test` will not run on merges to master, release publishes, or on version bump PRs
-- We disallow merging to `develop` unless these steps successfully pass, so we are essentially running redundant tasks whenever we release a new version.
- Publishing should now happen in parallel.
-- The [GitHub action that we use to publish crates](https://github.com/katyo/publish-crates) states that it determines the correct order for publishing according to dependencies.
CI should pass. 
I kept our default indexer checks for the release as it seems like a good idea to ensure those pass before a version is completely released to the public. Also, I adjusted the `publish-docker-image` step to only run on …
=> chore: reduce CI run time for releases

packages/fuel-indexer-macros/src/indexer.rs
The indexer currently dispatches a handler function _per transaction_ in a block; in effect, we're repeating an indexing function up to the max amount of transactions per block, if the only parameter is `BlockData`.
This PR ensures that we index _per block_ by moving the `decoder.dispatch()` call to the block iteration loop rather than the transaction iteration loop.
You can reproduce the bug by doing the following on the `develop` branch:
- Ensure DB is cleared.
- Add an logging call to an indexer
-- Feel free to add `info!("Block #{}", block_data.header.height);` to the `fuel-explorer` handler code.
- Compile the WASM module.
- Run the service with your adjusted indexer:
-- `cargo run -p fuel-indexer -- run --run-migrations --manifest …
=> fix: dispatch per block instead of per transaction

packages/fuel-indexer-benchmarks/benches/wasm/examples/fuel_explorer.rs, packages/fuel-indexer-benchmarks/src/lib.rs
Fix manifest creation in benchmarks.
Run `cargo bench` in the benchmarks folder and ensure that there are no compiler errors.
=> fix: fix manifest creation in benchmarks

packages/fuel-indexer-api-server/src/api.rs, packages/fuel-indexer-api-server/src/uses.rs, packages/fuel-indexer-database/postgres/src/lib.rs
- Adds auth to the new `/sql` query endpoint
- Should we also add this to the GraphQL query routes?
- Fixes a bug where `run_query` panics if no results are returned
```bash
> cargo run --bin fuel-indexer -- run --run-migrations --accept-sql-queries --fuel-node-host beta-3.fuel.network --fuel-node-port 80 --replace-indexer --auth-enabled --auth-strategy jwt --jwt-issuer FuelLabs
```
```bash
> curl http://localhost:29987/api/sql/fuel/explorer -d '{"query":"SELECT json_agg(t) FROM (SELECT * FROM fuel_explorer.output WHERE id IN (2, 23)) t;"}' -H "Content-type: application/json"
{"details":"Unauthorized.","success":"false"}%
```
- On `master` this would panic 
```bash
> curl http://localhost:29987/api/sql/fuel/explorer -d '{"query":"SELECT json_agg(t) FROM (SELECT * FROM fuel_explorer.output …
```
=> fix: add sql endpoint auth + make `run_query` fail gracefully

config.yaml, deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml, docs/src/getting-started/starting-the-fuel-indexer.md, packages/fuel-indexer-lib/src/config/cli.rs, packages/fuel-indexer-lib/src/config/mod.rs, packages/fuel-indexer-lib/src/defaults.rs, packages/fuel-indexer/src/executor.rs
Closes #1128.
- Allow for configuration of `NODE_BLOCK_PAGE_SIZE`
- Add flag to documentation
- Change playground `NODE_BLOCK_PAGE_SIZE` value to 25
Run the explorer example without the `--node-block-page size` flag; the service should request 10 blocks at a time. Run the explorer example again, but this time with `--node-block-page-size [NUM]`; the service should request `NUM` blocks at at time.
=> enhancement: make `NODE_BLOCK_PAGE_SIZE` configurable

Cargo.lock, plugins/forc-index/Cargo.toml, plugins/forc-index/src/cli.rs, plugins/forc-index/src/commands/auth.rs, plugins/forc-index/src/commands/deploy.rs, plugins/forc-index/src/commands/remove.rs, plugins/forc-index/src/ops/forc_index_auth.rs, plugins/forc-index/src/ops/forc_index_deploy.rs, plugins/forc-index/src/ops/forc_index_remove.rs, plugins/forc-index/src/ops/forc_index_welcome.rs, plugins/forc-index/src/utils.rs
For some reason the `forc-index deploy` command began to blow up on my machine. It seems like [`reqwest::blocking` was never supposed to play well with `tokio`](https://github.com/seanmonstar/reqwest/issues/1233) but somehow it did until now?
Anyways, this PR eliminates any usage of `reqwest::blocking` so this shouldn't be a problem anymore.
- Try the affected commands: `auth`, `deploy`, `remove` and `welcome`
- fix: certain `forc-index` commands crashing `tokio`
=> Replace blocking `reqwest` usage with async

docs/src/forc-index/start.md, docs/src/getting-started/starting-the-fuel-indexer.md
Add `--block-page-size` flag to `fuel-indexer run` and `forc index start`.
N/A
=> docs: adjust docs to include `--block-page-size` on start commands

packages/fuel-indexer-api-server/src/uses.rs
This PR removes an `info!` message that was accidentally merged.
=> remove debug info message

packages/fuel-indexer/src/executor.rs
- Reverts back to the logic we had: skipping blocks that produce errors due to https://github.com/FuelLabs/fuel-indexer/issues/1093 until https://github.com/FuelLabs/fuel-indexer/issues/1208 is in 
- [Confirmed fix shown in "Test 7 Fix" in this doc](https://docs.google.com/spreadsheets/d/1RV_AWAhknxkgvA0I-A8WTZE8ZOu0Jv-azAn3-2LVC0o/edit#gid=649003433)
- fix: temporarily skip bad ids
=> fix: temporarily skip bad ids

packages/fuel-indexer/src/service.rs
For consistency, add a log message for the start block when the resumable flag is not set.
I ran into this recently deploying hello_indexer. I was surprised not to see anything. Meanwhile, resuming fuel-explorer showed up in the logs. 
* add a log message
=> log message for start block when resumable not set
