.github/workflows/ci.yml, indexer/tests/test_indexer.rs
Also adds `--locked` to several cargo jobs to ensure that the `Cargo.lock` file is valid.
=> Refactor CI into concurrent jobs. Add mdbook and udeps checks.

docs/src/getting-started/system-dependencies.md
Updated version of https://github.com/FuelLabs/fuel-indexer/pull/74
=> Add explanation for deps

.github/workflows/ci.yml
This will automatically deploy fuel indexer to the EKS when a master build is ongoing
=> Adding remote dispatch for fuel indexer deployment

.github/workflows/ci.yml
Reverts FuelLabs/fuel-indexer#189
=> Revert "Update EKS Deployment"

database/postgres/src/lib.rs, fuel-indexer-lib/src/lib.rs, fuel-indexer-macros/src/schema.rs, fuel-indexer-schema/src/db.rs, fuel-indexer-schema/src/db/graphql.rs, fuel-indexer-schema/src/db/tables.rs, fuel-indexer/src/api.rs, fuel-indexer/src/bin/fuel-indexer.rs, fuel-indexer/src/database.rs, fuel-indexer/src/executor.rs, fuel-indexer/src/ffi.rs, fuel-indexer/src/service.rs
As requested in #188, this PR swaps `.unwrap()` for `.expect()` in the production code. Testing code was not adjusted as it won't be called when running in production.
=> Swap all unwrap() for expect()

docs/src/examples/hello-indexer.md
Per #199, this PR updates the example manifest. Perhaps once the structure of the project stabilizes a bit more, we should move said example to a separate page in the book.
=> Change manifest structure in book

deployment/Dockerfile, tests/e2e/composable-indexer/Dockerfile, tests/e2e/composable-indexer/docker-compose.yaml
=> Upgrade to rustc 1.64

.github/workflows/ci.yml
Adds CI job for to ensure proper compilation of WASM example. Closes #239.
=> Add CI job for wasm example

Cargo.lock, docs/src/components/assets/manifest.md, fuel-indexer-database/database-types/Cargo.toml, fuel-indexer-database/database-types/src/lib.rs, fuel-indexer-database/postgres/src/lib.rs, fuel-indexer-database/sqlite/src/lib.rs, fuel-indexer-lib/src/lib.rs, fuel-indexer-schema/Cargo.toml, fuel-indexer-schema/src/db/models.rs, fuel-indexer/Cargo.toml, fuel-indexer/src/api.rs, fuel-indexer/src/bin/fuel-indexer.rs, fuel-indexer/src/config.rs, scripts/utils/README.md
- This PR does a bit of cleanup and swaps manual `ToString` implementations (and the like) for `strum::EnumString` usage
- N/A
=> Swap manual trait impl for strum

.github/workflows/ci.yml
Just FYI there's two ways to debug this:
1. Just keep merging into master until it works (might have to do this 1 or 2 more times)
2. Pull every thing over the FuelLabs/ci-dummy-test and test there, then pull it back over the fuel-indexer when it works
Don't feel like putting in the effort for number 2 🙄  so going with number 1
=> Add new steps to release

fuel-indexer-database/postgres/src/lib.rs, fuel-indexer-database/sqlite/src/lib.rs
- Fix row fetching in `query_graph()` path
=> Fix row fetching in `query_graph()` path

docs/src/SUMMARY.md, docs/src/components/assets/wasm.md, docs/src/components/database/types.md, docs/src/examples/block-explorer.md, docs/src/quickstart/index.md, examples/block-explorer/schema/explorer.graphql
- Updates docs with M1 WASM help and some layout fixes
- Update block explorer example documentation with testing steps
- Fix block explorer example code nit
=> Update docs and block explorer example

packages/fuel-indexer/src/service.rs
@ra0x3 
Fixes #361 
Continues #362 
- Removed `SocketAddr` using `&str` instead
- Fuel Client auto checks for node URL so no explicit type cast is required
- Ran all tests and followed [contributing.md](https://github.com/FuelLabs/fuel-indexer/blob/a5753c425798a787f4d8aec888f16e4a23d567d9/docs/CONTRIBUTING.md)
` I accidentally closed the other PR and had some conflicts locally. Here's a fresh one. `
=> Fix `SocketAddr` issue while connecting to beta-2 testnet

docs/src/examples/block-explorer.md
- This markdown book explorer example was not up-to-date with the actual explorer example code. This PR changes that.
- N/A
=> update explorer example

packages/fuel-indexer-tests/src/fixtures.rs, packages/fuel-indexer-tests/src/lib.rs, packages/fuel-indexer-tests/tests/e2e.rs, packages/fuel-indexer-tests/tests/service.rs, packages/fuel-indexer/src/service.rs
- This is Part 1/3 for https://github.com/FuelLabs/fuel-indexer/issues/269
- CI should pass
=> add indexer srvc fixture

docs/README.md, docs/src/plugins/forc-index.md, plugins/forc-index/src/cli.rs, plugins/forc-index/src/commands/mod.rs, plugins/forc-index/src/commands/remove.rs, plugins/forc-index/src/ops/forc_index_remove.rs, plugins/forc-index/src/ops/mod.rs
Closes #428.
- Change for `forc index stop` to `forc index remove`
- Adjust documentation
CI should pass and command should function the same.
=> refactor (forc-index): Change `forc index stop` to `forc index remove`

Cargo.lock, packages/fuel-indexer-tests/Cargo.toml, packages/fuel-indexer-tests/src/lib.rs, packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs, packages/fuel-indexer-tests/tests/integration/web_api_sqlite.rs
Closes #440.
- Add test for checking proper asset upload functionality for Postgres databases
- Add test for checking proper asset upload functionality for SQLite databases
-- commented out for now as we investigate why it's breaking
Added new tests, CI should pass.
=> enhancement (fuel-indexer-tests): Add tests for asset upload

plugins/forc-index/src/commands/deploy.rs, plugins/forc-index/src/ops/forc_index_deploy.rs
- This PR makes `forc index build` a prerequisite of `forc index deploy`
- enhancement: forc index build prereq to forc index deploy
=> enhancement:  forc index build prereq to forc index deploy

Cargo.lock, examples/block-explorer/explorer-index/Cargo.toml, examples/hello-world-native/hello-index-native/Cargo.toml, examples/hello-world/hello-bin/Cargo.toml, examples/hello-world/hello-index/Cargo.toml, packages/fuel-indexer-api-server/Cargo.toml, packages/fuel-indexer-database/Cargo.toml, packages/fuel-indexer-database/database-types/Cargo.toml, packages/fuel-indexer-database/postgres/Cargo.toml, packages/fuel-indexer-database/sqlite/Cargo.toml, packages/fuel-indexer-lib/Cargo.toml, packages/fuel-indexer-macros/Cargo.toml, packages/fuel-indexer-metrics/Cargo.toml, packages/fuel-indexer-plugin/Cargo.toml, packages/fuel-indexer-schema/Cargo.toml, packages/fuel-indexer-tests/Cargo.toml, packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml, packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml, packages/fuel-indexer-types/Cargo.toml, packages/fuel-indexer/Cargo.toml, plugins/forc-index/Cargo.toml, plugins/forc-index/src/utils/defaults.rs
=> chore: version bump to v0.2.0

docs/README.md
- Read over the **Contributors** section the README and felt some small updates were needed
- docs: update readme
=> docs: update readme

.github/workflows/ci.yml, .github/workflows/gh-pages.yml, docs/src/SUMMARY.md
- Adjusts `mdbook` build steps to use the latest version instead of hard-coded versions
- Removes comments from `SUMMARY.md`
=> docs: fix book build

.github/workflows/ci.yml
This reverts commit 836cac4fe60e30e3387c28ad469c99144c4f8f43.
=> Revert "enhancement: build docker images for x86_64, ARM, and M1 archs"

plugins/forc-index/src/utils/defaults.rs
- PR fixes a bug in the default indexer code
- CC @bitzoic 
NOTES: There might be other bugs, this is just the one I've noticed so far.
- fix: update default indexer code
=> fix: update default indexer code

docs/src/reference-guide/data-types/types.md
Fixes table on "Data Types" page of the book.
=> fix, docs: fix table on data types page

docs/README.md
- User was experiencing some errors. Whilst helping them, realized our docs are not up-to-date.
- fix: update quickstart docs
=> fix: update quickstart docs

.github/workflows/ci.yml
- fix: don't use patch version for str comp
=> fix: don't use patch version for str comp

packages/fuel-indexer-tests/src/fixtures.rs
Fixes the wallet path in fixtures after the recent updates to test/asset paths.
=> bug: fix wallet path

.github/workflows/ci.yml
- temporarily turning off `forc-index-check` again until the release is cut
=> fix: update ci bool syntax

.github/workflows/ci.yml
Additional docker login for docker.io using authentication to avoid rate limiting.
=> Add docker.io login for image pull rate limiting

.github/workflows/ci.yml
- [We need to do it how the SDK does it](https://github.com/FuelLabs/fuels-rs/blob/master/.github/workflows/ci.yml#L254)
=> fix: ci publish tag verification

docs/README.md, docs/src/reference-guide/authentication/index.md, docs/src/reference-guide/plugins/forc-index/build.md, docs/src/reference-guide/plugins/forc-index/deploy.md, docs/src/reference-guide/plugins/forc-index/init.md, docs/src/reference-guide/plugins/forc-index/new.md, docs/src/reference-guide/plugins/forc-index/remove.md, docs/src/reference-guide/plugins/forc-index/revert.md, plugins/forc-index/README.md, plugins/forc-index/src/commands/auth.rs, plugins/forc-index/src/commands/build.rs, plugins/forc-index/src/commands/deploy.rs, plugins/forc-index/src/commands/init.rs, plugins/forc-index/src/commands/new.rs, plugins/forc-index/src/commands/remove.rs, plugins/forc-index/src/commands/revert.rs, plugins/forc-index/src/ops/forc_index_init.rs
- As you can see, the plugin docs were a bit dated, this PR changes that
- docs: bring plugin docs up to date
=> docs: update docs

docs/src/reference-guide/indexing/receipts/call.md
- Update `Call` receipt documentation
No code changes; CI should pass.
=> docs: update documentation for `Call` receipt

packages/fuel-indexer-tests/src/fixtures.rs
=> fix: update fuel-node fixture

docs/src/reference-guide/components/assets/module.md
=> docs: fix typo

Cargo.lock, packages/fuel-indexer-database/src/lib.rs, packages/fuel-indexer-lib/src/defaults.rs, packages/fuel-indexer-lib/src/manifest.rs, packages/fuel-indexer-macros/src/indexer.rs, packages/fuel-indexer/Cargo.toml, packages/fuel-indexer/src/executor.rs, packages/fuel-indexer/src/service.rs
- Just a cleanup PR
- Executors are created using 3 things:
- A node config
- An indexer manifest
- An executor source (WASM if wasm execution, or a function handler if native execution)
- chore: executor creation cleanup
=> chore: executor creation cleanup

config.yaml, packages/fuel-indexer-lib/src/config/auth.rs, packages/fuel-indexer-lib/src/config/mod.rs, plugins/forc-index/src/ops/forc_index_auth.rs, plugins/forc-index/src/ops/forc_index_deploy.rs
- Small devx updates related to authentication flow
- chore: small auth devx updates
=> chore: small auth devx updates

Cargo.lock, examples/block-explorer/explorer-indexer/Cargo.toml, examples/hello-world-native/hello-indexer-native/Cargo.toml, examples/hello-world/hello-indexer/Cargo.toml, packages/fuel-indexer-plugin/Cargo.toml, packages/fuel-indexer-plugin/src/native.rs, packages/fuel-indexer-plugin/src/wasm.rs
- Fix `sha2` dependency location for codegen
=> chore: fix dependency location for message ID calculation

docs/QUICKSTART.md, docs/README.md, docs/src/reference-guide/authentication/index.md, docs/src/reference-guide/components/graphql/playground.md, packages/fuel-indexer-api-server/src/lib.rs
- Took a look over the book/docs and just updated a few things that I found
- N/A
- docs: various documentation improvements
=> docs: various documentation improvements

packages/fuel-indexer-lib/src/config/auth.rs
- PR hides JWT secret from logs
- N/A
- fix: hide JWT secret from debug info
=> fix: hide JWT secret from debug info

packages/fuel-indexer-lib/src/config/mod.rs
- Fix bug reported by Luis related to GraphQL config vars
- fix: include proper graphql config key name
=> fix: include proper graphql config key name

deployment/charts/postgres/templates/postgres-deployment.yaml, deployment/scripts/.env
- add POSTGRES_PASSWORD to postgres helm chart
=> Fix fuel indexer helm chart for dev

docs/src/reference-guide/plugins/forc-index/deploy.md, packages/fuel-indexer-api-server/src/api.rs, packages/fuel-indexer-api-server/src/lib.rs, packages/fuel-indexer-api-server/src/uses.rs, plugins/forc-index/src/commands/deploy.rs, plugins/forc-index/src/ops/forc_index_deploy.rs
Reverts FuelLabs/fuel-indexer#788
=> Revert "enhancement: `forc index deploy --stop-previous`"

deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml, deployment/charts/fuel-indexer/values.yaml, deployment/scripts/.env
- add jwt token & issuer to indexer helm chart
=> Add indexer jwt helm chart

deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml, deployment/charts/fuel-indexer/templates/fuel-indexer-service-monitor.yaml
- This PR adds our metrics info to the base deployment file
- N/A
- chore: switch metrics over to base deployment
=> chore: switch metrics over to base deployment

docs/src/getting-started/dependencies/database.md, docs/src/getting-started/dependencies/index.md, docs/src/reference-guide/authentication/index.md, docs/src/reference-guide/indexing/receipts/call.md, docs/src/reference-guide/indexing/receipts/log.md, docs/src/reference-guide/indexing/receipts/logdata.md, docs/src/reference-guide/indexing/receipts/messageout.md, docs/src/reference-guide/indexing/receipts/panic.md, docs/src/reference-guide/indexing/receipts/return.md, docs/src/reference-guide/indexing/receipts/returndata.md, docs/src/reference-guide/indexing/receipts/revert.md, docs/src/reference-guide/indexing/receipts/scriptresult.md, docs/src/reference-guide/indexing/receipts/transfer.md, docs/src/reference-guide/indexing/receipts/transferout.md, packages/fuel-indexer-api-server/src/lib.rs, packages/fuel-indexer-metrics/src/core.rs
- PR updates docs to make them more consistent
- N/A
- docs: update for consistency
=> docs: update for consistency

docs/PULL_REQUEST.md
- PR adds a PR template
- N/A
- docs: add pr template
=> docs: add pr template

deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
- Dev is crashing due a duplicate start arg
=> fix: remove duplicate start arg

examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml, packages/fuel-indexer/src/database.rs
=> test: cast put_object bytes as bytea

Cargo.lock, packages/fuel-indexer-macros/Cargo.toml, packages/fuel-indexer-macros/macro-utils/Cargo.toml
- Update `syn` to v2.0
- Update to `syn v2.0`
=> chore: upgrade to syn v2.0

packages/fuel-indexer-api-server/src/uses.rs
- There were a few cases on asset registration where we weren't properly reverting transactions when an error happens, so if you had for example a schema error, the web API would be rendered useless with the following response:
```json
{
"details": "Database error: error returned from database: current transaction is aborted, commands ignored until end of transaction block.",
"success": "false"
}
```
- fix: revert transactions on asset registration
=> fix: revert transactions on asset registration

examples/hello-world-native/hello-indexer-native/src/main.rs, examples/hello-world/docker-compose.yaml, examples/hello-world/hello-indexer/src/lib.rs
Example docs were out of date
- N/A
- docs: update example docs
=> docs: update example docs

packages/fuel-indexer-lib/src/manifest.rs
I ran into `FileError` a couple of times, and it was frustrating not knowing which file the error referred to. It made it much harder to debug. This PR changes the `Manifest::FileError` variant to include the file name.
=> Change Manifest::FileError to include the file name

deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
=> chore: add --replace-indexer to deployment

plugins/forc-index/src/defaults.rs
- Forgot to update the WASM lib version. https://github.com/FuelLabs/fuel-indexer/pull/1051 only updates the native version 🥲 
- CI testing for all of this stuff we keep missing coming next
=> fix: forgot to update wasm lib

ci/build-and-deploy-examples.bash
=> fix: wait for hello-world-node to build on ci

packages/fuel-indexer/src/executor.rs
- More detailed logging so we can always know which indexer is being referred to in the logs
- N/A
- chore: add more executor logging
=> chore: add more executor logging

deployment/Dockerfile
This fixes Docker multiplatform builds.
Thanks to @Voxelot for the fix! See https://github.com/FuelLabs/fuel-core/pull/1251.
=> chore: fix docker multiplatform builds

examples/fuel-explorer/README.md, examples/hello-world/README.md
=> docs: remove reference to temporary docker image

.github/workflows/ci.yml
- [Docker is not running on `master` CI](https://github.com/FuelLabs/fuel-indexer/actions/runs/5581235821)
- [Docker and publish are not running on `release` CI](https://github.com/FuelLabs/fuel-indexer/actions/runs/5581239925)
- fix: re-add steps back to release
=> fix: re-add steps back to release

packages/fuel-indexer-lib/src/lib.rs
=> chore: bump MAX_ARRAY_LENGTH

.github/workflows/ci.yml
- I guess we do need _some_ release CI after all 
- You can check [this action](https://github.com/FuelLabs/fuel-indexer/actions/runs/5614185190/job/15211779587?pr=1132) to see that it works
=> ci: add cargo check

docs/README.md, docs/src/authentication/index.md, docs/src/forc-index/deploy.md, docs/src/forc-index/remove.md, docs/src/forc-index/status.md, plugins/forc-index/README.md
- The README is incorrect 
- N/A
- fix: update readme
=> fix: update readme

.github/workflows/ci.yml, docs/PULL_REQUEST_TEMPLATE.md, packages/fuel-indexer-benchmarks/src/lib.rs, packages/fuel-indexer-lib/src/lib.rs, packages/fuel-indexer/src/executor.rs
- Updates CI to only do `cargo check` when merging `master <- develop` and `develop <- master`
- I will test this out before cutting a release
- N/A
- ci: streamline develop <> master merges
=> ci: streamline develop <> master merges

.github/workflows/ci.yml
=> fix: trigger publish/docker on master & release

.github/workflows/ci.yml
=> fix: trigger publish/docker on master & release (again)

.github/workflows/ci.yml
=> fix: attempt  to fix docker/publish on release again

.github/workflows/ci.yml
=> fix: trigger publish/docker on master & release (#1184)

.github/workflows/ci.yml
=> fix: add spaces between $GITHUB_OUTPUT

.github/workflows/ci.yml
=> develop <> master

.github/workflows/ci.yml
=> ci: update latest docker tag
